# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Magarena
tagline:          'Fantasy card game against computer opponent'
description:      'A single-player fantasy card game played against a computer opponent'
url:              https://magarena.github.io
baseurl:          /

author:
  name:           'Magarena team'
  email:          magarena@googlegroups.com

gems: [jekyll-paginate]
paginate:         1

# Custom vars
version:          '1.96'

github:
  repo:           //github.com/magarena/magarena
